jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true

  - template: build/host-cleanup-linux.yml

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    retryCountOnTaskFailure: 3
    inputs:
      packageType: sdk
      version: 10.0.105
      includePreviewVersions: true

  - bash: |
      dotnet tool update --global uno.check --prerelease --add-source https://api.nuget.org/v3/index.json
    displayName: 'Install uno-check'
    retryCountOnTaskFailure: 3

  - bash: |
      uno-check --verbose --ci --non-interactive --fix --skip gtk3 --skip androidemulator --skip dotnetnewunotemplates --skip unosdk --skip openjdk
    displayName: 'Install .NET Workloads'
    retryCountOnTaskFailure: 3

  - template: build/canary-updater.yml
  - template: build/gitversion.yml

  - bash: |
      cd $(build.sourcesdirectory)
      dotnet publish -c Release src/Uno.Playground/Uno.Playground.csproj -f net10.0-browserwasm "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" -o "$(build.artifactstagingdirectory)/wasm-publish" -bl:$(build.artifactstagingdirectory)/linux.binlog
    env:
      GITVERSION_FullSemVer: $(GITVERSION_FullSemVer)
    displayName: 'Build Playground'

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.artifactstagingdirectory)/wasm-publish/wwwroot
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container
